name: Compile & Upload
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}
      - name: Set variables
        id: vars
        run: |
          VERSION=$(git rev-list --count HEAD)
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "::set-output name=plugin_version::${{ matrix.SM_VERSION }}.$VERSION.$SHORT_SHA"
      - name: Set GFLBans version
        run: |
          sed -i "s/<VERSION>/${{ steps.vars.outputs.plugin_version }}/g" addons/sourcemod/scripting/gflbans-core/variables.sp
          
      - name: Compile GFLBans
        run: |
          mkdir addons/sourcemod/plugins
          make CC=spcomp64 
          
      - name: Move addons folder to build
        run: |
          mkdir build
          cp -r ./addons build/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GFLBans.${{ steps.vars.outputs.plugin_version }}
          path: ./build
