name: Compile & Upload
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]
        
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}
      - name: Set variables
        id: vars
        run: |
          version=$(git rev-parse --count HEAD)
          shortSha=$(git rev-parse --short HEAD)
          echo "::set-output name=plugin_version::${{ matrix.SM_VERSION }}.$version.$shortSha"
      - name: Set GFLBans version
        run: |
          sed -i "s/<VERSION>/${{ steps.vars.outputs.plugin_version }}/g" $SCRIPTS_PATH/gflbans-core/variables.sp
          
      - name: Compile GFLBans
        run: |
          make CC=spcomp64 
          
      - name: Move addons folder to build
        run: |
          mkdir build
          cp -r ./addons build/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GFLBans.${{ steps.vars.outputs.plugin_version }}
          path: ./build
